spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 60000
      maximum-pool-size: 5
      pool-name: SpringHikariPool
    url: jdbc:postgresql://localhost:32770/carshop
    username: postgres
    password: postgres
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
  liquibase:
    change-log: classpath:db/changelog.xml
logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR